development:
  clients:
    default:
      uri: <%= Rails.application.credentials.dig(:mongoid, :uri) %>
      options:
        server_selection_timeout: 5

production:
  clients:
    default:
      uri: <%= Rails.application.credentials.dig(:mongoid, :uri) %>
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
