development:
  clients:
    default:
      database: search_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

production:
  clients:
    default:
      uri: <%= Rails.application.credentials.dig(:mongoid, :uri) %>
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: search_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
